language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-add-repository -y ppa:jkeiren/ppa
  - if test $CC = gcc; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if test $CC = clang; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list; fi
  - if test $CC = clang; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list; fi
  - if test $CC = clang; then echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi
  - sudo apt-get update -qq
install:
  - if test $CC = gcc; then sudo apt-get install --yes --force-yes gcc-5; fi
  - if test $CC = gcc; then sudo apt-get install --yes --force-yes g++-5; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
  - if test $CC = clang; then sudo apt-get -qq install build-essential; fi
  - if test $CC = clang; then sudo apt-get -qq --allow-unauthenticated install libstdc++-4.9-dev; fi
  - if test $CC = clang; then sudo apt-get -qq --allow-unauthenticated install clang-3.5; fi
  - if test $CC = clang; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 20; fi
  - if test $CC = clang; then sudo update-alternatives --config clang; fi
before_script:
  - mkdir Build
  - cd Build
  - cmake ..
script:
  - make
  - make test
