language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-add-repository -y ppa:jkeiren/ppa
  - if test $CC = gcc; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if test $CC = clang; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if test $CC = clang; then sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'; fi
  - if test $CC = clang; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -; fi
  - sudo apt-get update -qq
install:
  - if test $CC = gcc; then sudo apt-get install --yes --force-yes gcc-5 g++-5; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
  - if test $CC = clang; then sudo apt-get install --yes --force-yes libclang-3.5-dev clang-3.5; fi
  - if test $CC = clang; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 20; fi
  - if test $CC = clang; then sudo update-alternatives --config clang; fi
before_script:
  - mkdir Build
  - cd Build
  - cmake ..
script:
  - make
  - make test
