language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-add-repository -y ppa:jkeiren/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - if test $CC = clang; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list; fi
  - if test $CC = clang; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list; fi
  - if test $CC = clang; then echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi
  - sudo apt-get update -qq
install:
  - sudo apt-get install --yes --force-yes gcc-5
  - sudo apt-get install --yes --force-yes g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - if test $CC = clang; then sudo apt-get -qq install build-essential; fi
  - if test $CC = clang; then sudo apt-get -qq --allow-unauthenticated install clang-3.5; fi
  - if test $CC = clang; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 20; fi
  - if test $CC = clang; then sudo update-alternatives --config clang; fi
  - if test $CC = clang; then export CC='clang --with-gcc-toolchain /usr/bin/gcc'; fi
  - if test $CC = clang; then export CXX='clang++ --with-gcc-toolchain /usr/bin/gcc'; fi
before_script:
  - mkdir Build
  - cd Build
  - cmake ..
script:
  - make
  - make test
