language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-add-repository -y ppa:jkeiren/ppa
  - if test $CC = gcc; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if test $CC = clang; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
install:
  - if test $CC = gcc; then sudo apt-get install --yes --force-yes gcc-4.8 g++-4.8; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
  - if test $CC = clang; then sudo apt-get install --yes --force-yes clang-3.6; fi
  - if test $CC = clang; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.6 20; fi
  - if test $CC = clang; then sudo update-alternatives --config clang; fi
before_script:
  - mkdir Build
  - cd Build
  - cmake ..
script:
  - make
  - make test
